# These are supported funding model platforms

github: [omargoda]
patreon: omargoda
open_collective: omargoda
ko_fi: omargoda
tidelift: omargoda/omargoda
community_bridge: omargoda
liberapay: omargoda
issuehunt: omargoda
otechie: omargoda
custom: ['paypal.com/omargoda']
